### ISSUE TITLE
How to specify the path where to store the shared-state directory

### ISSUE THREAD

**Issue by m4rc0d1** [lorenwest/node-red-contrib-state#20]
I just migrated my node-red system to Docker and I found no way to specify the path for the shared-state directory. It seems that node-red-contrib-state uses the homedir of the user running node-red, but the Docker image defines /data for the volume that is persistent across rebuild and upgrades, while the home directory is recreated from scratch every time.

Is it possible to specify to store shared-state under /data or another arbitrary path?.

**Comment by lorenwest** [comment]
Yep, *sharedStateDir*

https://github.com/lorenwest/node-red-contrib-state?tab=readme-ov-file#shared-state-storage

**Comment by m4rc0d1** [comment]
Thanks for the prompt reply, I should have RTFM...
I was expecting a node property set in the node config, but a setting.js value is fine
