### ISSUE TITLE
state updated altough state did not change value

### ISSUE THREAD

**Issue by wzbfyb** [lorenwest/node-red-contrib-state#5]
Hi,

I noticed that on one use case, the state is updated although the value stays the same. Thus also the getState node fires. I mitigate this by adding a switch after the getState to compare value with prev, but it's strange!

![grafik](https://user-images.githubusercontent.com/57131473/91796323-27428180-ec20-11ea-923c-3fbe64877168.png)

I have not debugged it yet, but I think the reason is that I typed it boolean with "on"/"off" as keywords

![grafik](https://user-images.githubusercontent.com/57131473/91796412-6375e200-ec20-11ea-8963-8db09745fdf0.png)

but the payload I save from MQTT is actually "ON"/"OFF".
it seems to work, but your comparison here:
`    if (newState === node.value) {return}`

may thinks that "OFF" != "off":

clicking on the ON inject always fires a state change, although the typed value of your node does not change:
![grafik](https://user-images.githubusercontent.com/57131473/91796651-04649d00-ec21-11ea-97b5-de06bba3cf9b.png)

If I leave the state type as String, the case of ON and OFF is preserved and the node does NOT fire again. So it is an issue with boolean type only.

**Comment by lorenwest** [comment]
Thank you for that thorough explanation. You are correct that the node should not fire based on the input not matching the output, it should fire based on an actual change in the output. 

Fixed and published today in node-red-contrib-state@1.5.1 

Let me know if this resolves this issue.

**Comment by wzbfyb** [comment]
thanks a lot, will give it a try.
it is not on npm yet, still 1.5.0 on my palette

LG

**Comment by lorenwest** [comment]
Node-RED has a problem identifying new NPM versions.  Try this in a terminal window:
```
npm info node-red-contrib-state version
```
You may need to go to your node-red directory that contains node_modules and do an `npm install node-red-contrib-state` instead of the pallette.

**Comment by wzbfyb** [comment]
that worked, thanks. and it now works as expected, thanks a lot!
